### ISSUE TITLE
Uppladning av documents fungerar inte

### ISSUE THREAD

**Issue by thomaswennersten** [inooLabs/intric-release#6]
Vi har gjort en installation av Intric och det fungerar att ställa frågor via chat, har gett credentials till OpenAI.

Vid försök att ladda upp dokument så "står det bara och snurrar", ingen respons, inga felmeddelanden.

Ska en specific embedding modell kopplas med credetials i så fall var ska det specas?

**Comment by jklingst** [comment]
Vet inte om det är relaterat, men vi fick samma beteende om det inte var startat någon "worker" via steg 8 i setup:en för backend.

**Comment by thomaswennersten** [comment]
Det var detta som hängt sig, tack!
